import {
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faCheck,
  faCloud,
  faCogs,
  faDatabase,
  faEye,
  faFlag,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignOutAlt,
  faSignInAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  faGamepad,
  faDownload,
  faStar,
  faFilter,
  faTableCells,
  faXmark,
  faChevronDown,
  // jhipster-needle-add-icon-import
} from '@fortawesome/free-solid-svg-icons';

import { faStar as faStarRegular } from '@fortawesome/free-regular-svg-icons';

import { faSteamSymbol, faInstagram, faTwitter, faLinkedin, faGithub } from '@fortawesome/free-brands-svg-icons';

export const fontAwesomeIcons = [
  faArrowLeft,
  faAsterisk,
  faBan,
  faBars,
  faBell,
  faBook,
  faCalendarAlt,
  faCheck,
  faCloud,
  faCogs,
  faDatabase,
  faEye,
  faFlag,
  faHeart,
  faHome,
  faList,
  faLock,
  faPencilAlt,
  faPlus,
  faRoad,
  faSave,
  faSearch,
  faSignOutAlt,
  faSignInAlt,
  faSort,
  faSortDown,
  faSortUp,
  faSync,
  faTachometerAlt,
  faTasks,
  faThList,
  faTimes,
  faTrashAlt,
  faUser,
  faUserPlus,
  faUsers,
  faUsersCog,
  faWrench,
  faGamepad,
  faDownload,
  faSteamSymbol,
  faInstagram,
  faTwitter,
  faLinkedin,
  faGithub,
  faStar,
  faStarRegular,
  faFilter,
  faTableCells,
  faXmark,
  faChevronDown,
  // jhipster-needle-add-icon-import
];
